on:
  push:
    branches: [main, master]

name: Render Quarto doc

jobs:
  Render:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: schoulten/macro_report_priv
          path: "./report"
          token: ${{ secrets.PAT }}

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
          use-public-rspm: true

      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1

      - name: Install Python packages
        run: poetry install --no-root

      - name: Python code
        run: |
          poetry config virtualenvs.prefer-active-python true
          poetry run python Python/etl.py

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto doc
        run: |
          cp -f ./report/. ./
          quarto render index.qmd
          rm -rf report contents resources index.qmd

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data ETL and report update
          commit_user_name: Fernando da Silva
          commit_user_email: fernando.schoulten@hotmail.com
          commit_author: Fernnado da Silva <fernando.schoulten@hotmail.com>
